2023-06-26 21:39:03,672 ERROR Internal Server Error: /news/ C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('mainnews1.html, news/post_list.html'), <traceback object at 0x000001769A7A1340>)
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: mainnews1.html, news/post_list.html
2023-06-26 21:39:03,674 ERROR "GET /news/ HTTP/1.1" 500 89409 C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\core\servers\basehttp.py None
2023-06-26 21:39:03,755 ERROR Internal Server Error: /news/ C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('mainnews1.html, news/post_list.html'), <traceback object at 0x000001769A7EB100>)
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: mainnews1.html, news/post_list.html
2023-06-26 21:39:03,756 ERROR "GET /news/ HTTP/1.1" 500 88328 C:\Users\anton\Desktop\курс\Django\news\lib\site-packages\django\core\servers\basehttp.py None
